// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgtype"
)

type ApiKey struct {
	ID          uuid.UUID
	Encodedhash string
	Owner       string
	Description sql.NullString
	System      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Group struct {
	ID          uuid.UUID
	DisplayName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type GroupUser struct {
	GroupID uuid.UUID
	UserID  uuid.UUID
}

type ScimApiKey struct {
	ID        uuid.UUID
	Domain    string
	ApiKeyID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	Username    string
	ExternalID  sql.NullString
	Name        pgtype.JSONB
	DisplayName sql.NullString
	Locale      sql.NullString
	Active      bool
	Emails      pgtype.JSONB
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
